# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "ehci_pci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f4f9400e-9d52-41ef-a70d-80617c1a6c17";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/FE2A-6B70";
      fsType = "vfat";
    };

  fileSystems."/mnt/datadaddy/Music" =
    { device = "192.168.0.137:/Music/Collection";
      fsType = "nfs";
    };

  fileSystems."/mnt/datadaddy/general/ingest/YouTube" =
    { device = "192.168.0.137:/general/ingest/YouTube";
      fsType = "nfs";
    };

  fileSystems."/mnt/datadaddy/general/ingest/podcast" =
    { device = "192.168.0.137:/audio/Archive/podcast";
      fsType = "nfs";
    };

  fileSystems."/mnt/Media" =
    { device = "/dev/disk/by-uuid/eb13a0d2-63d5-4f02-a899-3bcdbdd799a6";
      fsType = "xfs";
    };

  swapDevices =
    #[ { device = "/dev/disk/by-uuid/98d39efb-9b47-488d-8bb6-c18b1fc046f9"; }
    [ { device = "/dev/disk/by-uuid/2f1ec8a2-dff9-4b0a-875e-388a454ccb13"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
}
